language: ruby
notifications:
  email:
    recipients:
      - r.saunders@queensu.ca
    on_success: change
    on_failure: always
rvm:
  - 2.3.3
services:
  - postgresql
script:
  - RAILS_ENV=development bundle exec rails db:schema:load --trace
before_script:
  - psql -c 'create database "engsoc-dash_development";' -U postgres
